name: Deploy to Koyeb

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker buildx build --platform linux/amd64 -t ${{ secrets.DOCKER_USERNAME }}/your-image-name:latest . --push

    - name: Deploy to Koyeb
      run: |
        curl -X POST \
        https://app.koyeb.com/v1/apps/YOUR_APP_ID/services/YOUR_SERVICE_ID/deploy \
        -H "Authorization: Bearer ${{ secrets.KOYEB_API_KEY }}"